# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3.3], [4, 5, 6.5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd.DataFrame(a2)

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [7]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
np.arange(0, 100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0, 10, size=(7, 2))

array([[2, 6],
       [8, 8],
       [6, 0],
       [7, 8],
       [1, 4],
       [3, 7],
       [4, 8]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.rand(3, 5)

array([[0.14774229, 0.9901488 , 0.73117069, 0.23599625, 0.22197922],
       [0.56851518, 0.83263932, 0.80973014, 0.61978184, 0.9734061 ],
       [0.78166771, 0.70963403, 0.19479067, 0.3656952 , 0.0200796 ]])

In [12]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, size=(4, 6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(random_array)

array([1, 2, 3, 4, 5, 7, 9])

In [14]:
# Find the 0'th index of the latest array you created
random_array[0]

array([9, 1, 3, 7, 4, 9, 3])

In [15]:
# Get the first 2 rows of latest array you created
random_array[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[9, 1],
       [5, 3]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
new_arr = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))

In [18]:
# Add the two arrays together
new_arr + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))

In [20]:
# Try add the array of ones and the other most recent array together
new_arr + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

> The arrays must be of compatible ("broadcast"-able shapes).

In [21]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3, 5))

In [22]:
# Subtract the new array of ones from the other most recent array
new_arr - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [23]:
# Multiply the ones array with the latest array
new_arr * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [24]:
# Take the latest array to the power of 2 using '**'
new_arr ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [25]:
# Do the same thing with np.square()
np.square(new_arr)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]], dtype=int32)

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(new_arr)

3.8666666666666667

In [27]:
# Find the maximum of the latest array using np.max()
np.max(new_arr)

9

In [28]:
# Find the minimum of the latest array using np.min()
np.min(new_arr)

0

In [29]:
# Find the standard deviation of the latest array
np.std(new_arr)

2.578543947441829

In [30]:
# Find the variance of the latest array
np.var(new_arr)

6.648888888888889

In [31]:
# Reshape the latest array to (3, 5, 1)
np.reshape(new_arr, (3, 5, 1))

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [32]:
# Transpose the latest array
new_arr.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

What does the transpose do?

> Transpose re-arranges the array elements so that rows become columns, columns become rows, etc. It is the same operation as in Matrix operations in Linear Algebra.

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_33 = np.random.randint(0, 10, size=(3, 3))
arr_32 = np.random.randint(0, 10, size=(3, 2))

In [34]:
# Perform a dot product on the two newest arrays you created
arr_33.dot(arr_32)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_43 = np.random.randint(0, 10,  size=(4, 3))
other_arr_43 = np.random.randint(0, 10,  size=(4, 3))

In [36]:
# Perform a dot product on the two newest arrays you created
arr_43.dot(other_arr_43)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr_43.dot(other_arr_43.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10,  size=(6, 9))
arr2 = np.random.randint(0, 10,  size=(6, 9))

In [39]:
# Compare the two arrays with '>'
arr1 > arr2

array([[ True,  True, False, False, False, False, False, False, False],
       [ True, False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False, False,  True],
       [ True,  True,  True, False, False, False,  True,  True, False],
       [False,  True,  True, False,  True,  True, False, False,  True],
       [ True, False,  True, False,  True,  True,  True, False,  True]])

What happens when you compare the arrays with `>`?

> The elements of each array get compared to each other element-wise.

In [40]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True,  True, False, False, False,  True, False, False,  True],
       [ True, False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False, False,  True,  True],
       [ True,  True,  True, False, False, False,  True,  True, False],
       [False,  True,  True, False,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True,  True, False,  True]])

In [41]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False, False,  True],
       [ True,  True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True,  True, False],
       [False, False,  True, False,  True, False, False, False,  True],
       [ True, False,  True, False, False, False, False,  True, False]])

In [42]:
# Show the elements of the array
arr1

array([[6, 6, 7, 4, 2, 7, 5, 2, 0],
       [2, 4, 2, 0, 4, 9, 6, 6, 8],
       [9, 9, 2, 6, 0, 3, 3, 4, 6],
       [6, 3, 6, 2, 5, 1, 9, 8, 4],
       [5, 3, 9, 6, 8, 6, 0, 0, 8],
       [8, 3, 8, 2, 6, 5, 7, 8, 4]])

In [43]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False, False, False, False,  True, False, False,  True],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False, False]])

In [44]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[0, 2, 2, 4, 5, 6, 6, 7, 7],
       [0, 2, 2, 4, 4, 6, 6, 8, 9],
       [0, 2, 3, 3, 4, 6, 6, 9, 9],
       [1, 2, 3, 4, 5, 6, 6, 8, 9],
       [0, 0, 3, 5, 6, 6, 8, 8, 9],
       [2, 3, 4, 5, 6, 7, 8, 8, 8]])

In [45]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1)

array([[8, 4, 7, 3, 6, 0, 1, 2, 5],
       [3, 0, 2, 1, 4, 6, 7, 8, 5],
       [4, 2, 5, 6, 7, 3, 8, 0, 1],
       [5, 3, 1, 8, 4, 0, 2, 7, 6],
       [6, 7, 1, 0, 3, 5, 4, 8, 2],
       [3, 1, 8, 5, 4, 6, 0, 2, 7]], dtype=int64)

In [46]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr1)

14

In [47]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr1)

8

In [48]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)

array([2, 5, 0, 6, 2, 0], dtype=int64)

In [49]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)

array([1, 3, 1, 1, 2, 3, 4, 4, 0], dtype=int64)

In [50]:
# Create an array of normally distributed random numbers
np.random.randn(6, 9)

array([[-0.5361601 ,  1.09652886,  0.42801284, -2.46969887,  0.48197914,
         0.92645636, -0.83758139,  0.67718607,  1.87231912],
       [ 0.39637394, -0.6256163 , -0.52246148,  0.0130339 ,  0.37776959,
         0.0628246 ,  0.50159637, -0.14694539,  0.18062297],
       [ 0.96481058, -1.06483115,  0.1087118 ,  0.10576365,  0.92066672,
        -0.22672246,  0.65304831,  1.10268747, -1.84980294],
       [ 1.16863124, -0.9853818 , -1.09394041, -2.87945689, -0.80317767,
        -0.00485694, -0.38332331, -0.46252686, -1.11249735],
       [ 0.8672295 ,  0.95841384,  0.41811852, -1.88652805,  2.27334516,
         0.14697465,  0.5396092 , -1.49829564, -0.01144345],
       [ 0.41335409, -0.14089855,  0.87216186,  1.30034515, -1.34352376,
         0.85012058,  0.39433995, -0.00469599, -1.57081198]])

In [51]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.